Repository intel-retail/retail-use-cases, pull requests merged in 2024-10, with the labels that each got.

#40 feat: Continual learning use case
  .github/workflows/trivyimagescan.yaml
  .gitignore
  use-cases/continual_learning/Dockerfile
  use-cases/continual_learning/Makefile
  use-cases/continual_learning/README.md
  use-cases/continual_learning/app.py
  use-cases/continual_learning/camera-demo.py
  use-cases/continual_learning/config.py
  use-cases/continual_learning/continual_learning_demo.png
  use-cases/continual_learning/images/Green_Grape/Images.txt
  use-cases/continual_learning/images/Red_Apple/Images.txt
  use-cases/continual_learning/lib/common/plotting.py
  use-cases/continual_learning/lib/common/utils.py
  use-cases/continual_learning/lib/dataset/__init__.py
  use-cases/continual_learning/lib/dataset/folder_dataset.py
  use-cases/continual_learning/lib/dataset/repository.py
  use-cases/continual_learning/lib/dataset/synthesizer.py
  use-cases/continual_learning/lib/dataset/utils.py
  use-cases/continual_learning/notebook/slda_frozen_classification_cl.ipynb
  use-cases/continual_learning/requirements.txt
  use-cases/continual_learning/third-party-programs.txt
Labels: enhancement

#42 feat: Add gRPC python helm deployment
  use-cases/grpc_python/Makefile
  use-cases/grpc_python/docker-compose_grpc_python.yml
  use-cases/grpc_python/entrypoint.sh
  use-cases/grpc_python/grpc_python.py
  use-cases/grpc_python/kubernetes.md
  use-cases/grpc_python/object-detection-service-distributed-grpc-3.1.0.tgz
  use-cases/grpc_python/object-detection-service-distributed-grpc/Chart.yaml
  use-cases/grpc_python/object-detection-service-distributed-grpc/README.md
  use-cases/grpc_python/object-detection-service-distributed-grpc/templates/camera-simulator-deployment.yaml
  use-cases/grpc_python/object-detection-service-distributed-grpc/templates/camera-simulator-service.yaml
  use-cases/grpc_python/object-detection-service-distributed-grpc/templates/camera-simulator0-deployment.yaml
  use-cases/grpc_python/object-detection-service-distributed-grpc/templates/ovms-client-grpc-python-deployment.yaml
  use-cases/grpc_python/object-detection-service-distributed-grpc/templates/ovms-server-deployment.yaml
  use-cases/grpc_python/object-detection-service-distributed-grpc/templates/ovms-server-service.yaml
  use-cases/grpc_python/pipeline-server/Dockerfile
  use-cases/grpc_python/pipeline-server/config.json
  use-cases/grpc_python/pipeline-server/downloadModels.sh
Labels: enhancement, 3.2

#48 fix: resolve the yolov8n model downloading issue
  models-downloader/Dockerfile.yolov8-download
  models-downloader/downloadOVMSModels.sh
  models-downloader/model_build/convert-model.py
  models-downloader/model_build/convert-model.sh
  models-downloader/model_build/download-tools.sh
  models-downloader/model_build/quantize-model.py
  use-cases/gst_capi/helm/Dockerfile_yolov8
  use-cases/gst_capi/helm/Makefile
  use-cases/gst_capi/helm/config-yolov8.json
  use-cases/gst_capi/helm/yolov8n-int8-416.bin
  use-cases/gst_capi/helm/yolov8n-int8-416.xml
  use-cases/gst_capi/pipelines/capi_yolov8_ensemble/efficientnetb0_node.cpp
Labels: bug, 3.2

#47 feat: Add Pytorch yolov5 object detection pipelines
  README.md
  use-cases/demos/Dockerfile-pytorch
  use-cases/demos/Makefile
  use-cases/demos/add_demo_pytorch_object_detection.yml
  use-cases/demos/object_detection/pytorch-yolo/Pytorch_Yolo_Example.ipynb
  use-cases/demos/object_detection/pytorch-yolo/entrypoint.sh
  use-cases/demos/object_detection/pytorch-yolo/yolov5_object_detection.py
  use-cases/demos/pytorch-yolov5-env.txt
  use-cases/demos/requirements-pytorch.txt
Labels: enhancement

#49 fix: add fps in pipeline logs
  use-cases/demos/object_detection/pytorch-yolo/entrypoint.sh
  use-cases/demos/object_detection/pytorch-yolo/yolov5_object_detection.py
Labels: enhancement

#51 fix: update base capi Makefiles and Dockerfiles to include mqtt libs
  use-cases/gst_capi/Dockerfile.yolov8
  use-cases/gst_capi/helm/Dockerfile_yolov8
  use-cases/gst_capi/helm/Makefile
  use-cases/gst_capi/pipelines/capi_yolov8_ensemble/Makefile
Labels: bug
