Repository intel-retail/retail-use-cases, pull requests merged in 2024-03, with the labels that each got.

#7 feat: add grpc_python replica docker-compose update
  Makefile
  README.md
  use-cases/grpc_python/Dockerfile
  use-cases/grpc_python/Makefile
  use-cases/grpc_python/docker-compose_replicas_grpc_python.yml
  use-cases/grpc_python/entrypoint.sh
  use-cases/grpc_python/res/grpc_python.env
  use-cases/ovms_server/Dockerfile
  use-cases/ovms_server/config.json
  use-cases/ovms_server/entrypoint.sh
Labels: enhancement, 3.0

#9 feat: add replica docker compose for gst-capi use cases
  .gitignore
  Makefile
  README.md
  use-cases/gst_capi/Makefile
  use-cases/gst_capi/add_camera-simulator.yml
  use-cases/gst_capi/add_replicas_capi_face_detection.yml
  use-cases/gst_capi/add_replicas_capi_yolov5.yml
  use-cases/gst_capi/add_replicas_capi_yolov5_ensemble.yml
  use-cases/gst_capi/pipelines/capi_yolov5/main.cpp
  use-cases/gst_capi/pipelines/capi_yolov5_ensemble/main.cpp
  use-cases/gst_capi/pipelines/face_detection/main.cpp
  use-cases/gst_capi/run_gst_capi.sh
Labels: enhancement, 3.0

#11 feat: add replica docker compose for grpc demos
  .gitignore
  Makefile
  README.md
  use-cases/demos/Makefile
  use-cases/demos/add_dependent_services.yml
  use-cases/demos/add_replicas_classification.yml
  use-cases/demos/add_replicas_instance_segmentation.yml
  use-cases/demos/add_replicas_object_detection.yml
  use-cases/demos/classification/python/entrypoint.sh
  use-cases/demos/instance_segmentation/python/entrypoint.sh
  use-cases/demos/object_detection/python/entrypoint.sh
  use-cases/demos/res/classification.env
Labels: enhancement, 3.0

#14 refactor: simplifying the docker compose name by removing word replicas in the filename
  .gitignore
  Makefile
  use-cases/demos/Makefile
  use-cases/demos/add_demo_classification.yml
  use-cases/demos/add_demo_instance_segmentation.yml
  use-cases/demos/add_demo_object_detection.yml
  use-cases/dlstreamer/Makefile
  use-cases/dlstreamer/docker-compose_dlstreamer.yml
  use-cases/grpc_python/Makefile
  use-cases/grpc_python/docker-compose_grpc_python.yml
  use-cases/gst_capi/Makefile
  use-cases/gst_capi/add_gst_capi_face_detection.yml
  use-cases/gst_capi/add_gst_capi_yolov5.yml
  use-cases/gst_capi/add_gst_capi_yolov5_ensemble.yml
Labels: 3.0, refactor

#18 fix: Dependabot updates
  use-cases/dlstreamer/requirements.txt
Labels: 3.0, dependencies

#16 feat: add smoke tests for running use-cases pipelines
  .gitignore
  Makefile
  smoke-tests/Makefile
  smoke-tests/requirements.txt
  smoke-tests/use-cases_smoke_tests.py
Labels: enhancement, 3.0

#15 refactor: update compose and Makefile to use retail root env variable…
  use-cases/demos/Makefile
  use-cases/demos/add_demo_classification.yml
  use-cases/demos/add_demo_instance_segmentation.yml
  use-cases/demos/add_demo_object_detection.yml
  use-cases/demos/add_dependent_services.yml
  use-cases/demos/res/classification_conf.yaml
  use-cases/demos/res/instance_segmentation_conf.yaml
  use-cases/demos/res/object_detection_conf.yaml
  use-cases/dlstreamer/Makefile
  use-cases/dlstreamer/docker-compose_dlstreamer.yml
  use-cases/grpc_go/Makefile
  use-cases/grpc_go/docker-compose_grpc_go.yml
  use-cases/grpc_go/res/grpc_go_conf.yaml
  use-cases/grpc_python/Makefile
  use-cases/grpc_python/docker-compose_grpc_python.yml
  use-cases/gst_capi/Makefile
  use-cases/gst_capi/add_camera-simulator.yml
  use-cases/gst_capi/add_gst_capi_face_detection.yml
  use-cases/gst_capi/add_gst_capi_yolov5.yml
  use-cases/gst_capi/add_gst_capi_yolov5_ensemble.yml
  use-cases/gst_capi/res/capi_face_detection_conf.yaml
  use-cases/ovms_server/config.json
Labels: 3.0, refactor
