Repository intel-retail/retail-use-cases, pull requests merged in 2025-02, with the labels that each got.

#64 fix: Change pep8 to pycodestyle for fixing failure due to reviewdog GitHub action
  .github/.reviewdogConfig.yml
  .github/workflows/reviewdog.yaml
Labels: bug, Beginner, cicd

#65 fix: Move ISSUE_TEMPLATE.md to ISSUETEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, documentation, Beginner

#67 fix: revert back tensorflow & other package versions
  use-cases/continual_learning/README.md
  use-cases/continual_learning/images/Green_Grape/Images.txt
  use-cases/continual_learning/images/Red_Apple/Images.txt
  use-cases/continual_learning/requirements.txt
Labels: bug
